export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_ERROR = 'SET_ERROR';

export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_SET_DATA = 'FETCH_ORDERS_SET_DATA';
export const RESET_ORDERS_STATE = 'RESET_ORDERS_STATE';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_LOADING_STATUS = 'PURCHASE_BURGER_LOADING_STATUS';
export const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SET_AUTHENTICATED = 'AUTH_SET_AUTHENTICATED';
export const AUTH_CLEAR_TOKEN = 'AUTH_CLEAR_TOKEN ';

export const NOTIFICATION_ADD_ERROR_MESSAGE_MODAL = 'NOTIFICATION_ADD_ERROR_MESSAGE_MODAL';

