
export const errorActions = {
    CRITICAL_ERROR: 'CRITICAL_ERROR',
    ERROR_RESET: 'ERROR_RESET',
    NOTIFICATION_ADD_ERROR_MESSAGE_MODAL: 'NOTIFICATION_ADD_ERROR_MESSAGE_MODAL',
    VISIBILITY_NOTIFICATION_ADD_ERROR_MESSAGE_MODAL: 'VISIBILITY_NOTIFICATION_ADD_ERROR_MESSAGE_MODAL',
};
