export const notificationsActions = {
    NOTIFICATION_RESET: 'NOTIFICATION_RESET',
    SET_NOTIFICATION_MESSAGE_TOAST: 'SET_NOTIFICATION_MESSAGE_TOAST',
    VISIBILITY_NOTIFICATION_MESSAGE_TOAST: 'VISIBILITY_NOTIFICATION_MESSAGE_TOAST',
};
